//
// ExchangeTest.cs
//
// This file was generated by XMLSpy 2011sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using Altova.Types;

namespace Exchange
{
	/// <summary>
	/// Summary description for ExchangeTest.
	/// </summary>
	class ExchangeTest
	{
		protected static void Example()
		{
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   Exchange.Exchange2 doc = Exchange.Exchange2.CreateDocument();			
			//   Exchange.VariableType root = doc.Variable.Append();
			//   ...
			//   doc.SaveToFile("Exchange1.xml", true);
			//
			// Example code to load and save a structure:
			//   Exchange.Exchange2 doc = Exchange.Exchange2.LoadFromFile("Exchange1.xml");
			//   Exchange.VariableType root = doc.Variable.First;
			//   ...
			//   doc.SaveToFile("Exchange1.xml", true);

		}

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		public static int Main(string[] args)
		{
			try
			{
				Console.WriteLine("Exchange Test Application");
				Example();
				Console.WriteLine("OK");
				return 0;
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}
	}
}
